namespace: petclinic-dev

resources:
  - namespace.yaml
  - ../../base/database
  - ../../base/app

# commonLabels:
#   backstage.io/kubernetes-id: spring-boot

images:
  - name: petclinic
    newName: quay.io/pittar/petclinic
    newTag: dev

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: petclinic
    path: environment-patch.yaml
